runtime: python39
entrypoint: streamlit run app/main.py --server.port=$PORT --server.address=0.0.0.0

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 3
  target_cpu_utilization: 0.65

env_variables:
  STREAMLIT_SERVER_PORT: $PORT
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_ENABLE_CORS: "false"
