[project]
name = "finanical-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "streamlit>=1.43.2",
    "watchdog>=6.0.0",
]
