[project]
name = "home-media-server"
version = "0.1.0"
requires-python = "~=3.13.1"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "jinja2>=3.1.6",
]
